// Mocks generated by Mockito 5.4.5 from annotations
// in roost_mvp/test/presentation/bloc/app_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:roost_mvp/domain/entities/app_entity.dart' as _i5;
import 'package:roost_mvp/domain/repositories/app_repository.dart' as _i2;
import 'package:roost_mvp/domain/usecases/get_apps.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppRepository_0 extends _i1.SmartFake implements _i2.AppRepository {
  _FakeAppRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetApps].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetApps extends _i1.Mock implements _i3.GetApps {
  MockGetApps() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAppRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AppRepository);

  @override
  _i4.Future<List<_i5.AppEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i5.AppEntity>>.value(
              <_i5.AppEntity>[],
            ),
          )
          as _i4.Future<List<_i5.AppEntity>>);
}
