// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtkBLmZ-hnDY1xN9j_lat4gKqsyKQHKDo',
    appId: '1:3289579495:web:fcb3ee9ae9a2a901980742',
    messagingSenderId: '3289579495',
    projectId: 'roost-mvp',
    authDomain: 'roost-mvp.firebaseapp.com',
    storageBucket: 'roost-mvp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX6o_uwtyjF9PtMyzoQDzCjTgEjKCo-y0',
    appId: '1:3289579495:android:965b41e79d7f15bd980742',
    messagingSenderId: '3289579495',
    projectId: 'roost-mvp',
    storageBucket: 'roost-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAMBZUhjTXeU9jPQ1w9iJXo_ZazuIkKRI',
    appId: '1:3289579495:ios:471428be87a474ac980742',
    messagingSenderId: '3289579495',
    projectId: 'roost-mvp',
    storageBucket: 'roost-mvp.firebasestorage.app',
    iosBundleId: 'com.yoelkiflezghi.roostMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAMBZUhjTXeU9jPQ1w9iJXo_ZazuIkKRI',
    appId: '1:3289579495:ios:e4860ba9ab3e90bb980742',
    messagingSenderId: '3289579495',
    projectId: 'roost-mvp',
    storageBucket: 'roost-mvp.firebasestorage.app',
    iosBundleId: 'com.example.roostMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtkBLmZ-hnDY1xN9j_lat4gKqsyKQHKDo',
    appId: '1:3289579495:web:dcfbf61d6e663e82980742',
    messagingSenderId: '3289579495',
    projectId: 'roost-mvp',
    authDomain: 'roost-mvp.firebaseapp.com',
    storageBucket: 'roost-mvp.firebasestorage.app',
  );
}
